language: node_js
node_js:
  - "8.9"
dist: xenial
cache: yarn
env:
  global:
    - CC_TEST_REPORTER_ID=1c0d52a15d69bb64fa5869be36aa6505501e0a11d2592e1e3769de6d48fea93c
before_script:
  - yarn build
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
