name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "install dependencies"
      run: yarn install

    - name: "build"
      run: yarn build

    - name: "test"
      run: yarn test

    - name: "check for unformatted sources"
      run: |
        yarn format:check \
        || (echo "##[error] found unformatted files. please 'npm run format'" \
                 "and check in all changes" \
            && exit 1)

    - name: "check for uncommitted changes"
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run build'" \
                 "and check in all changes" \
            && exit 1)
